### ISSUE TITLE
Request new concept: Franatech [BODCNVS-2384]

### ISSUE THREAD

**Issue by callumrollo** [nvs-vocabs/L35#1]
Hi, we have a methane sensor from Franatech AS that we would like a vocabulary entry for in L35. The sensor exists in L22

https://vocab.nerc.ac.uk/collection/L22/current/TOOL1244/

And the company Franatech is represented in B75

https://vocab.nerc.ac.uk/collection/B75/current/ORG01145/

But Franatech has no entry in L22. I think it is expected for oceanographic sensor manufacturers to be documented in both B75 and L35? e.g. Sea-Bird has both B75:ORG00226 and L35:MAN0013

If that's not the case, we can just link to B75:ORG01145 no problem!

**Comment by JordanAthertonNOC** [comment]
Hi @callumrollo 

I can't identify why this term doesn't have an associated L35 term, it must have been missed off. I will create one and link it to the existing L22 entry.

**Comment by JordanAthertonNOC** [comment]
New L35 created - MAN0303 and linked to TOOL1244

This will be reflected online on the NVS tomorrow after the overnight cron.

**Comment by JordanAthertonNOC** [comment]
For awareness - we had some downtime overnight so new terms / amendments made yesterday have not been reflected online on the NVS. The term exists in our database though and can still be used.

**Comment by callumrollo** [comment]
Nice. I was worried I'd tanked the vocab server with my excessive requests :grimacing:
